---

- name: install system dependencies

  package:
    name: "{{ item }}"
    state: present
  with_items:
    - curl
    - libpng-devel
    - libxml2-devel
    - openssl-devel
    - libcurl-devel
    - pandoc 

- name: install R packages dependencies

  shell: >
    install2.r -r https://cran.uni-muenster.de/ -l /usr/lib64/R/library -s Rcpp graphics utils jsonlite Matrix 

- name: install reticulate 

  shell: install2.r -r https://cran.uni-muenster.de/ -l /usr/lib64/R/library reticulate 

