namespace: "svaksha"
name: "yaksha"
version: "20.08"
description: "Yaksha uses daemons to automate the system installation & management for cross-platform OS for multiple programming languages using ansible playbooks, with dotfiles and configuration files!"
readme: "README.md"
authors: ["SVAKSHA"]
license: ["AGPLv3"]
tags:
    - daemons
    - automation
    - ansible
    - shell
    - dotfiles
    - debian
    - ubuntu
    - automation
    - python
repository: "https://github.com/svaksha/yaksha"
documentation: "https://github.com/svaksha/yaksha"
homepage: "http://svaksha.github.io/yaksha"
issues: "https://github.com/svaksha/yaksha/issues"
