################################################################################
# NAME       : install.conf.yaml
# DESCRIPTION: Simple configuration file for a new Debian-Ubuntu system.
# AUTHOR     : SVAKSHA, http://svaksha.com/pages/Bio
# SOURCE     : http://svaksha.github.io/yaksha
# COPYRIGHT© : 2005-Now SVAKSHA, All Rights Reserved.
# LICENSE    : GNU AGPLv3 subject to meeting the terms and conditions in the LICENSE
#              (https://github.com/svaksha/yaksha/blob/master/LICENSE.md) file.
# DATES      : 2014aug15~Present
################################################################################
#
# 

- clean: ['~']

- link:
    ~/.atom:                ~/yaksha/home/.atom/
    ~/.julia:               ~/yaksha/home/.julia/
    ~/.vim:                 ~/yaksha/home/.vim/
    ~/.bash_aliases:        ~/yaksha/home/.bash_aliases
    ~/.bash_logout:         ~/yaksha/home/.bash_logout
    ~/.bash_profile:        ~/yaksha/home/.bash_profile
    ~/.bashrc:              ~/yaksha/home/.bashrc
    ~/.curlrc:              ~/yaksha/home/.curlrc
    ~/.gemrc:               ~/yaksha/home/.gemrc
    ~/.git-prompt.sh:       ~/yaksha/home/.git-prompt.sh
    ~/.gitattributes:       ~/yaksha/home/.gitattributes
    ~/.git-completion.bash: ~/yaksha/home/.git-completion.bash
    ~/.gitignore_global:    ~/yaksha/home/.gitignore_global
    ~/.gitconfig:           ~/yaksha/home/.gitconfig
    ~/.gitk:                ~/yaksha/home/.gitk
    ~/.gitmessage:          ~/yaksha/home/.gitmessage
    ~/.hgignore_global:     ~/yaksha/home/.hgignore_global
    ~/.hgrc:                ~/yaksha/home/.hgrc
    ~/.inputrc:             ~/yaksha/home/.inputrc
    ~/.juliarc.jl:          ~/yaksha/home/.juliarc.jl
#    ~/.juliarc-update.jl:   ~/yaksha/home/.juliarc-update.jl
#    ~/.juliarc-yaksha.jl:   ~/yaksha/home/.juliarc-yaksha.jl
    ~/.profile:             ~/yaksha/home/.profile
    ~/.pythonrc.py:         ~/yaksha/home/.pythonrc.py
    ~/.screenrc:            ~/yaksha/home/.screenrc
    ~/.tigrc:               ~/yaksha/home/.tigrc
    ~/.tigrc-default:       ~/yaksha/home/.tigrc-default
    ~/.tigrc-test:          ~/yaksha/home/.tigrc-test
    ~/.tmux.conf:           ~/yaksha/home/.tmux.conf
    ~/.tmux:                ~/yaksha/home/.tmux
    ~/.vimrc:               ~/yaksha/home/.vimrc
    ~/.wgetrc:              ~/yaksha/home/.wgetrc

- shell:
    - [git submodule update --init --recursive dotbot, Installing submodules]

