---

- hosts: all
  remote_user: root
  # Switch off Ansible's fact gathering with 'gather_facts' set to 'false'. 
  # Fact gathering relies on Python so the playbook will crash if its not pre-installed.
  gather_facts: false
  tasks:
    - name: Check for Python
      raw: test -e /usr/bin/python
      changed_when: false
      failed_when: false
      register: check_python
