---
- name: "Install Packages"
  hosts: localhost
  connection: local
  become: yes
  tasks:

  - name: Install basic packages
    apt:
      name:
      - vim
      - curl
      - python3-pip
      - apache2
      - libapache2-mod-wsgi-py3
      - mysql-server
      - libmysqlclient-dev
      state: latest
      cache_valid_time: 3600

  - name: Update apt-get repo and cache
    apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

  - name: Install erlang packages
    apt:
      name:
      - erlang-base
      - erlang-asn1
      - erlang-crypto
      - erlang-eldap
      - erlang-ftp
      - erlang-inets
      - erlang-mnesia
      - erlang-os-mon
      - erlang-parsetools
      - erlang-public-key
      - erlang-runtime-tools
      - erlang-snmp
      - erlang-ssl
      - erlang-syntax-tools
      - erlang-tftp
      - erlang-tools
      - erlang-xmerl
      state: latest
      cache_valid_time: 3600

