---
- name: Install Imaging packages
  hosts: localhost
  #strategy: debug
  tasks:

  - name: DPKG fixes pkg problems
    shell: sudo dpkg --configure -a

  - name: Run apt-get install
    shell: sudo apt-get install -f

  - name: Clean & Update
    shell: sudo apt-get clean && sudo apt-get update

  - name: Upgrade
    shell: sudo apt-get upgrade -y

  - name: Install basic packages
    apt:
      name:
      - build-essential 
      - cmake 
      - unzip 
      - pkg-config
      # install some image and video I/O libraries for loading & reading image/video files.
      - libjpeg-dev 
      - libpng-dev 
      - libtiff-dev
      - libavcodec-dev
      - libavformat-dev
      - libswscale-dev
      - libv4l-dev
      - libxvidcore-dev
      - libx264-dev
      # nstall GTK for a GUI backend
      - libgtk-3-dev
      - python3-dev
      # install OpenCV on Ubuntu-20.04
      
...
