---
#- name: Install env for lxd
#  apt:
#  - name: snap
#    state: present

#- name: fix snap
#  command: snap install core

#- name: snap install lxd, atom
#  snap:
#  - name: lxd
#    classic: yes
# Now use Debian APT-GET
- name: inital installs
  hosts: localhost
  tasks:
    - name: Install basic Ubuntu packages
      package: 
        name: "{{ item }}" 
        state: present
        update_cache: yes
      become: yes
      become_method: sudo
      with_items:
      - git
      - tig
      - stow
      - mc
      # gAWK and SED
      - gawk, mawk
      # download using CLI terminal commands
      - wget, curl, w3m, elinks
      - whois
      - zip
      - unzip
      - unrar
      - sendmail
      - postfix
      # universal packaging system
      - flatpak
      - gnome-software-plugin-flatpak
      - cron-apt
      # BASH script checker: http://m.jakstys.lt/tech/2016/08/bash
      - shellcheck
      # https://askubuntu.com/questions/892076/how-to-selectively-purge-old-kernels-all-at-once/892077#892077
      - dialog # DEP of server version of "rm-kernels-server"     
      #########################################################################
      ## media codecs, video and audio (music - mpto mp3) converters
      #########################################################################
      - ubuntu-restricted-extras # install the MP3 codec from the Ubuntu Restricted Extras package
      - soundconverter # install the Sound Converter program
      - pavucontrol
      - transcriber # for manual transcription
      - vokoscreen #screencasting
      - transmission
      - audacity
      - alsa
      - rhythmbox
      - isomaster
      - dconf-editor
      #########################################################################
      # IDE for GNOME to support GTK+, GLib, APIs
      #########################################################################
      - emacs
      - geany
      - guake
      - meld  # comparison tool for GNOME
      - spyder
      # CLI text editors for sysadmins working on remote Linux/Unix servers.
      - nano
      - vim
      # Tweak Clock settings in 18.04
      - gnome-tweak-tool
      - gnome-clocks
      #########################################################################
      ## general cli tools for web, search
      #########################################################################
      - silversearcher-ag
      - ctags
      - screen
      # Tools for dependency check and PPA removal
      - equivs
      - ppa-purge
      - nmap
      - dirmngr
      #########################################################################
      # Automate SERVER - NETWORKING - CLOUD
      #########################################################################
      # SSH
      - sshpass
      # SSH
      - openssh-server
      - net-tools
      - apparmor, apparmor-profiles, apparmor-utils
      - wireguard
      - openvpn
      #########################################################################
      # Install Augeas - http://augeas.net/download.html
      # An editing tool API to automate the configuration editing on remote servers.
      #########################################################################
      - python3-augeas 
      - augeas-tools
      - augeas-lenses
      #########################################################################
      # BASIC python packages
      #########################################################################
      - python-yaml
      - python3-pip
      - python-jinja2 
      - python-crypto
      - python-psutil
      - cython
      - pyqt5-dev-tools
      # python-imaging
      - python-pil-doc, python3-pil, python3-pil-dbg, python3-pil.imagetk
      - python3-sane, python3-sane-dbg, python-pil.imagetk
      #########################################################################
      # OCR packages
      #########################################################################
      - libtesseract-dev
      - tesseract-ocr
      - libleptonica-dev
      # Language packs
      - tesseract-ocr-eng, tesseract-ocr-ara, tesseract-ocr-chi-sim
      - tesseract-ocr-script-latn, tesseract-ocr-script-deva
      # iagemagick lib
      - graphicsmagick-imagemagick-compat  # version 1.4+really1.3.35-1, or
      - imagemagick-6.q16                  # version 8:6.9.10.23+dfsg-2.1ubuntu11
      - imagemagick-6.q16hdri  
      #₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹
      # GCC {{ C, CPP, Fortran }}
      #₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹
      ## C/C++
      - gcc, make
      - cmake
      - libncurses5-dev
      - cmake-curses-gui
      - clang
      - g++
      ## Fortran
      - gfortran
      - m4
      - patch
      ## BOOST
      - fftw-dev
      - openexr
      - libboost-all-dev
      - fftw3-dev
      - liblemonldap-ng-common-perl, liblemonldap-ng-handler-perl
      - libpng-dev
      #₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹
      # Basic JAVASCRIPT with package manager 
      #₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹₹
      - npm 
      
      
