---
# https://cran.rstudio.com/bin/linux/debian/
- name: download and install rstudio-server-1.2.1335-amd64.deb
  apt:
    deb: "https://download2.rstudio.org/server/debian9/x86_64/rstudio-server-1.2.1335-amd64.deb"
  become:  true
  become_method: sudo
  when: ansible_os_family == "Debian" and ansible_lsb.major_release|int >= 16
