---
# https://www.rstudio.com/products/rstudio/download-server/
- name: download and install rstudio-server-1.2.1335
  apt:
    deb: "https://download2.rstudio.org/server/bionic/amd64/rstudio-server-1.2.1335-amd64.deb"
  become:  true
  become_method: sudo
  register: out_rst
  when: ansible_os_family == "Ubuntu" and ansible_lsb.major_release|int >= 16
- debug: msg= "{{ out_rst.stderr }}"
